import menu1 from "../assets/menu1.png";
import menu2 from "../assets/menu2.png";
import menu3 from "../assets/menu3.png";

const menuOneH3 = document.createElement("h3");
menuOneH3.textContent = "Fancy Salad";
const menuOneP = document.createElement("p");
menuOneP.textContent = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt velit dicta in, labore molestias quibusdam libero? Nisi veritatis accusamus pariatur!";
const menuOneLeftSide = document.createElement("div");
menuOneLeftSide.appendChild(menuOneH3);
menuOneLeftSide.appendChild(menuOneP);
menuOneLeftSide.classList.add("side");
const menuOneRightSide = document.createElement("div");
const menuOneImg = document.createElement("img");
menuOneImg.src = menu1;
menuOneRightSide.appendChild(menuOneImg);
const menuOne = document.createElement("div");
menuOne.appendChild(menuOneLeftSide);
menuOne.appendChild(menuOneRightSide);
menuOne.classList.add("menu-card");
menuOne.style.textAlign = "left";

const menuTwoH3 = document.createElement("h3");
menuTwoH3.textContent = "Spicy Salad";
const menuTwoP = document.createElement("p");
menuTwoP.textContent = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt velit dicta in, labore molestias quibusdam libero? Nisi veritatis accusamus pariatur!";
const menuTwoLeftSide = document.createElement("div");
const menuTwoImg = document.createElement("img");
menuTwoImg.src = menu2;
menuTwoLeftSide.appendChild(menuTwoImg);
const menuTwoRightSide = document.createElement("div");
menuTwoRightSide.appendChild(menuTwoH3);
menuTwoRightSide.appendChild(menuTwoP);
menuTwoRightSide.classList.add("side");
const menuTwo = document.createElement("div");
menuTwo.appendChild(menuTwoLeftSide);
menuTwo.appendChild(menuTwoRightSide);
menuTwo.classList.add("menu-card");
menuTwo.style.textAlign = "right";

const menuThreeH3 = document.createElement("h3");
menuThreeH3.textContent = "Tasty Salad";
const menuThreeP = document.createElement("p");
menuThreeP.textContent = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt velit dicta in, labore molestias quibusdam libero? Nisi veritatis accusamus pariatur!";
const menuThreeLeftSide = document.createElement("div");
menuThreeLeftSide.appendChild(menuThreeH3);
menuThreeLeftSide.appendChild(menuThreeP);
menuThreeLeftSide.classList.add("side");
const menuThreeRightSide = document.createElement("div");
const menuThreeImg = document.createElement("img");
menuThreeImg.src = menu3;
menuThreeRightSide.appendChild(menuThreeImg);
const menuThree = document.createElement("div");
menuThree.appendChild(menuThreeLeftSide);
menuThree.appendChild(menuThreeRightSide);
menuThree.classList.add("menu-card");
menuThree.style.textAlign = "left";

const heading = document.createElement("h2");
heading.textContent = "Our Menu";
const hr = document.createElement("hr");
hr.classList.add("hr");
const menu = document.createElement("div");
menu.appendChild(heading);
menu.appendChild(hr);
menu.appendChild(menuOne);
menu.appendChild(menuTwo);
menu.appendChild(menuThree);
menu.classList.add("flex");

export default menu;